name: Merge upstream

on:
    push:
    schedule:
        -   cron: '0 * * * *'

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Merge upstream
                run: |
                    git config --global user.name 'Goooler'
                    git config --global user.email 'goooler@users.noreply.github.com'

                    # "git checkout master" is unnecessary, already here by default
                    git pull --unshallow  # this option is very important, you would get
                                          # complains about unrelated histories without it.
                                          # (but actions/checkout@v2 can also be instructed
                                          # to fetch all git depth right from the start)

                    git remote add upstream https://github.com/coil-kt/coil.git
                    git fetch upstream
                    git checkout -b master origin/master
                    git merge --no-edit upstream/master
                    git push origin master
